language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python -m unittest discover
notifications:
  slack:
    secure: WShCvmznQTXI9X4DAonZ1u2foKk6v/WAu3TiKtHauCMqQctvBIHh+Hv8ff8NcVU7hy+HEQoYO6XiiVDYFoQo1r6FeXyixmuXGVSOi6dt/BakqwtZAYNvWorP4E5kVXtRd4WZV4Fe9qemOMr6Yuwk4U04/RVIT1JAQjFyvoCv31P2JeT58cf1kDkp0ARGqFwwN78sLo3nGz4QgHNRC87yVn9eCXNewtO2wOaQm8wTbYM+dbF2xTPx5Rsz/Xlg8mFNfq6bErJScLA+K/Tht3AZcOmbpl9lLtfzizZELFozlhZ7HsnhszxZgphKdIGpuhkqQedwY+R+1vbe2/nOjrzxOJo4fdZYRUKVYhgiaJXuFtSnzioH5/0qzRWS6i//bmThMDRVDRZ71mSoJ0hJMk+rMxMuQTAF1ei7Mcbl4TktfhXDiGLgqj4Inh1LPzyncvsV+ElOAok2Zmq7ddwmMioClKPEewa7myCQFyMhTcv740XQ20iUjexVLz5JMgSOIjI3Ilbb5Kl71mg75WUwQ6YITc2nbqb066p4xgR+XnUhKPrXwzsJIZcTfJjNshhVC03l3TySwkSwdjfec6yyNBxIsoHGM9RzwGd/xOy3fTZW2iyhOlpdFbrasmoAtEeH/q7UMIX8TX+f8Cc5tNSUEZAiTLW35ErZ7yV7zOOmRehaIf0=
